#!/usr/bin/env zsh
#   _________  _   _ ____   ____ 
#  |__  / ___|| | | |  _ \ / ___|
#    / /\___ \| |_| | |_) | |    
# _ / /_ ___) |  _  |  _ <| |___ 
#(_)____|____/|_| |_|_| \_\\____|
#
 
# Complétion 
autoload -U compinit
compinit


# Resource from https://github.com/mika/zsh-pony
# Edit command line
autoload edit-command-line && zle -N edit-command-line
bindkey '^v' edit-command-line

zstyle ':completion:*:descriptions' format '%U%B%d%b%u'
zstyle ':completion:*:warnings' format '%BSorry, no matches for: %d%b'
zstyle ':completion:*:sudo:*' command-path /usr/local/sbin /usr/local/bin \
                             /usr/sbin /usr/bin /sbin /bin /usr/X11R6/bin
# Crée un cache des complétion possibles
# très utile pour les complétion qui demandent beaucoup de temps
# comme la recherche d'un paquet aptitude install moz<tab>
zstyle ':completion:*' use-cache on
zstyle ':completion:*' cache-path ~/.zsh_cache
# des couleurs pour la complétion
# faites un kill -9 <tab><tab> pour voir :)
zmodload zsh/complist
# Some aliases
# other paste from https://doc.ubuntu-fr.org/zsh
# basic documentation about zsh on ubuntu

alias f=fg %1
alias ff=fg %2
alias fff=fg %3
alias pserver=python -m SimpleHTTPServer
alias home=cd $HOME

alias la="ls -a"
alias ls='ls --color=auto'
alias ll='ls --color=auto -lh'
alias lll='ls --color=auto -lh | less'
alias sl='ls'
alias ..='cd ..'
alias ...='cd ../..'

alias grep='grep --color=auto'
alias -g G=' | grep '


export EDITOR=vim
export VISUAL=vim
export MYVIMRC=/home/mkeita/.vimrc

export PATH="$HOME/.rbenv/bin:$PATH"
export HISTIGNORE="cd_*"


setopt append_history share_history histignorealldups
setopt auto_cd
# cdpath=($HOME/Documents $HOME/Images $HOME/Pictures $HOME/Documents/coding_dojo $HOME/Desktop/Brouillon)

setopt correctall

set -o vi

# Bind key jj to esc vi mode 
# http://superuser.com/questions/351499/how-to-switch-comfortably-to-vi-command-mode-on-the-zsh-command-line

bindkey -M viins 'jj' vi-cmd-mode

# Other good configuration
# Taken from http://superuser.com/questions/151803/how-do-i-customize-zshs-vim-mode/156204#156204 

function zle-line-init zle-keymap-select {
    RPS1="${${KEYMAP/vicmd/-- NORMAL --}/(main|viins)/-- INSERT --}"
    RPS2=$RPS1
    zle reset-prompt
}

zle -N zle-line-init
zle -N zle-keymap-select

eval "$(rbenv init -)"
